server:
  port: 9531
spring:
  datasource:
    url: jdbc:mysql://47.114.156.221:3306/comm_ums?rewriteBatchedStatements=true&useSSL=false&serverTimezone=GMT
    username: root
    password: hct1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: comm-ware

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
